name: Node.js CI

on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install root dependencies
        run: npm ci

      - name: Install dependencies for operator
        run: npm ci
        working-directory: ./simple-block-agreement/operator

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test